name: "Helm Chart Setup and Deployment"
description: "Setup a Helm chart, modify its appVersion, and deploy it to a Kubernetes cluster"

inputs:
  helm-chart-version:
    description: "The Helm chart version"
    required: true
  helm-registry-url:
    description: "The Helm OCI registry URL"
    required: true
  helm-package:
    description: "The Helm package"
    required: true
  helm-username:
    description: "The username to authenticate with the Helm registry"
    required: true
  helm-password:
    description: "The password to authenticate with the Helm registry"
    required: true
  helm-protocol:
    description: "The protocol for fetching the Helm chart (e.g., oci://). Default is 'oci://'."
    default: "oci://"
  release-name:
    description: "The name of the Helm release"
    required: true
  namespace:
    description: "The namespace in which to deploy the Helm chart and application"
    required: true
  values-file:
    description: "Path to the Helm values file"
    required: true
  image-tag:
    description: "Tag of the container image"
    default: "latest"
  timeout:
    description: "Timeout for the Helm command"
    default: "5m"
  working-directory:
    description: "The working directory"
    default: "."

runs:
  using: "composite"
  steps:
    - name: Login to Helm registry
      shell: bash
      run: |
        helm registry login ${{ inputs.helm-registry-url }} \
          -u ${{ inputs.helm-username }} \
          -p ${{ inputs.helm-password }}

    - name: Pull the Helm chart
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        helm pull ${{ inputs.helm-protocol }}${{ inputs.helm-registry-url }}/${{ inputs.helm-package }} \
          --version ${{ inputs.helm-chart-version }}

    - name: Extract Helm chart
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        tar -xzf ${{ inputs.helm-package }}-*.tgz

    - name: Update appVersion in Chart.yaml
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        yq -i '.appVersion = "${{ github.sha }}" | .appVersion style="double"' \
          ${{ inputs.helm-package }}/Chart.yaml

    - name: Deploy Helm chart
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        HELM_DRIVER: configmaps
      run: |
        helm upgrade --wait --install ${{ inputs.release-name }} ./${{ inputs.helm-package }} \
          --namespace ${{ inputs.namespace }} \
          --history-max 10 \
          --values ${{ inputs.values-file }} \
          --atomic --timeout ${{ inputs.timeout }} \
          --set image.tag=${{ inputs.image-tag }}
