name: 'Setup Kubernetes for Digital-Ocean.'
description: 'Setup Digital-Ocean CLI and configure Kubernetes.'

inputs:
  cluster-name:
    description: 'Kubernetes cluster name'
  digital-ocean-token:
    description: 'Digital Ocean access token'

runs:
  using: "composite"
  steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.digital-ocean-token }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ inputs.cluster-name }}
      shell: bash
