name: 'Deploy to Kubernetes'
description: 'Deploy application to a Kubernetes Cluster. Requires Kubernetes to be configured first.'

inputs:
  environment:
    description: '"test" or "prod"'
  namespace-name:
    description: 'Digital Ocean namespace name'
  deployment-name:
    description: 'Kubernetes deployment name'

runs:
  using: "composite"
  steps:
    - name: Deploy to Kubernetes
      run: kubectl apply -f infrastructure/kubernetes.${{ inputs.environment }}.yml
      shell: bash

    - name: Verify deployment
      id: verify
      run: kubectl rollout status -n ${{ inputs.namespace-name }} deployment/${{ inputs.deployment-name }}
      shell: bash

    - name: Undo deployment if failed
      if: ${{ failure() && steps.verify.conclusion == 'failure' }}
      run: kubectl rollout undo -n ${{ inputs.namespace-name }} deployment/${{ inputs.deployment-name }}
      shell: bash
