name: 'Setup kubectl and Helm.'
description: 'Setup kubectl and Helm using kubeconfig file.'

inputs:
  kubeconfig:
    description: 'The kubeconfig file content'
    required: true
  kubectl-version:
    description: 'kubectl version'
    required: false
    default: '1.33.1'
  helm-version:
    description: 'Helm version'
    required: false
    default: '3.17.3'

runs:
  using: "composite"
  steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: ${{ inputs.kubectl-version }}

    - name: Setup kubeconfig file
      run: |
        mkdir -p ~/.kube
        echo "${{ inputs.kubeconfig }}" > ~/.kube/config
        chmod 600 ~/.kube/config
      shell: bash

    - name: Setup Helm
      uses: azure/setup-helm@v4
      with:
        version: ${{ inputs.helm-version }}
