name: 'Teardown PostgreSQL Preview Schema'
description: 'Drops the PostgreSQL preview schema'
inputs:
  deployment-name:
    description: 'Name of the deployment (used for ConfigMap name)'
    required: true
  namespace:
    description: 'Kubernetes namespace'
    required: true
  preview-number:
    description: 'Preview number (PR number)'
    required: true
  secret-name:
    description: 'Name of the secret containing DB password'
    required: false
    default: 'app-secrets'
  postgres-image:
    description: 'PostgreSQL image to use'
    required: false
    default: 'postgres:18'

runs:
  using: "composite"
  steps:
    - name: Prepare teardown-schema job
      env:
        JOB_NAME: "drop-schema-preview-${{ inputs.preview-number }}"
        CONFIGMAP_NAME: "${{ inputs.deployment-name }}-environments"
        SECRET_NAME: "${{ inputs.secret-name }}"
        PREVIEW_SCHEMA_NAME: "preview_${{ inputs.preview-number }}"
        POSTGRES_IMAGE: "${{ inputs.postgres-image }}"
      run: |
        envsubst '
          $JOB_NAME
          $CONFIGMAP_NAME
          $SECRET_NAME
          $PREVIEW_SCHEMA_NAME
          $POSTGRES_IMAGE
        ' < ${{ github.action_path }}/job-template.yml > job-teardown-schema.yml

        echo "Prepared job manifest: job-teardown-schema.yml"
      shell: bash

    - name: Create teardown-schema job
      run: |
        kubectl apply --namespace ${{ inputs.namespace }} -f job-teardown-schema.yml
      shell: bash

    - name: Wait for teardown-schema job to complete
      env:
        JOB_NAME: "drop-schema-preview-${{ inputs.preview-number }}"
        NAMESPACE: "${{ inputs.namespace }}"
      run: |
        echo "Waiting for job $JOB_NAME in namespace $NAMESPACE..."
        
        if kubectl wait --namespace $NAMESPACE --for=condition=complete --timeout=60s job/$JOB_NAME; then
          echo "Job finished with status: Complete"
          kubectl logs job/$JOB_NAME --namespace $NAMESPACE
        elif kubectl wait --namespace $NAMESPACE --for=condition=failed --timeout=1s job/$JOB_NAME; then
          echo "Job finished with status: Failed"
          kubectl logs job/$JOB_NAME --namespace $NAMESPACE
          exit 1
        else
          echo "Timeout waiting for job to complete."
          kubectl logs job/$JOB_NAME --namespace $NAMESPACE || true
          exit 1
        fi
      shell: bash
